### ISSUE TITLE
General config file for storing Strings 

### ISSUE THREAD

**Issue by horikandthepurpleshrooms** [Vladisimo/python-price-spider#1]
https://github.com/Vladisimo/python-price-spider/blob/89bf04b10f0421f1dac8ed6f5c7455a30c5a2f88/emagscraper/emagscraper/spiders/emagspider.py#L8

Hi!

Just_ an idea, maybe it would help to have a general configuration file where you store all the constants, strings, numbers, and import that file where is needed.

This would help if you're facing duplicate values, or the case where you'll need to change a particular string in more than one place. Using a general config file, you'll only need to change it in one place.

`
import constants...
  name = constants.name
`

**Comment by VladGhelbere** [comment]
This is just an initial commit. I wanna make sure I understand how everything works before doing amy tweaks. But thanks !
